import Head from 'next/head'
import { AxiosResponse } from 'axios'
import { GetServerSideProps } from 'next'
import { fetchCategories } from '../http'
import {
  ICategory, ICollectionResponse
} from '../types';

interface IPropTypes {
  categories: {
    items: ICategory[],
  };
}

export default function Home({ categories }: IPropTypes) {
  // console.log('categories', categories);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {
        categories.items.map(category => {
          return <span>{category.attributes.Title}</span>
        })
      }

      <main >
        <h1 className="text-primary-dark">
          Welcome to Coders blog!
        </h1>
      </main>
    </>
  )
}

export const getServerSideProps: GetServerSideProps = async () => {
  const {
    data: categories,
  }: AxiosResponse<ICollectionResponse<ICategory[]>> = await fetchCategories();
  return {
    props: {
      categories: {
        items: categories.data,
      }
    }
  }
}